name: "Nix build"
on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

permissions:
  contents: write 
  
jobs:
  test-nix-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - uses: cachix/install-nix-action@daddc62a2e67d1decb56e028c9fa68344b9b7c2a
      with:
        nix_path: nixpkgs=channel:nixos-22.11
    - run: nix-build shell.nix
    - run: nix-shell --run "fix-hie"
    - uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
      with:
        commit_message: Update hie.yaml 
        commit_options: '--no-verify --signoff'
        file_pattern: 'hie.yaml'
        skip_dirty_check: true
        skip_fetch: true
        skip_checkout: true
        disable_globbing: true
    - run: nix-shell --run "hlint src && git diff --exit-code hie.yaml"
