name: "Nix build"
on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

permissions:
  contents: read
  
jobs:
  test-nix-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-22.11
    - run: nix-build shell.nix
    - run: nix-shell --run "echo OK"
