name: "Stack build"
on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test-stack-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: freckle/stack-cache-action@ed5f0b5ad23c22386472fc61b0b8da7fd6bfbc67
      - uses: freckle/stack-action@d32c32d930606e981e7bb34c624c31b5c5f9bdc6
    
