name: "Stack build"
on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test-stack-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: freckle/stack-cache-action@v2.0.8
      - uses: freckle/stack-action@v2.0.8
    
